version: '3'

services:
  app:
    build: .
    ports:
      - "0.0.0.0:8502:8502"
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=j58XWwdZMELLmJ!P
      - LLM_API_KEY=${LLM_API_KEY}
    env_file:
      - .env
    volumes:
      - ./config.toml:/app/config.toml
      - ./graph_config.ini:/app/graph_config.ini
    networks:
      - app-network

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/j58XWwdZMELLmJ!P
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  neo4j_data:
  neo4j_logs: 