version: '3'

services:
  app:
    build: .
    ports:
      - "8502:8502"
    depends_on:
      - neo4j
    env_file:
      - .env
    volumes:
      - ./config.toml:/app/config.toml
      - ./graph_config.ini:/app/graph_config.ini

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/your_neo4j_password
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  neo4j_data:
  neo4j_logs: 